<?php
/**
 * Script setup untuk membuat folder uploads dan sample images
 * Jalankan file ini sekali setelah mengupload project
 */

echo "<h2>🚀 Setup Sistem Toko Elektronik</h2>";

// 1. Buat folder uploads
$uploadDir = 'uploads';
if (!file_exists($uploadDir)) {
    if (mkdir($uploadDir, 0755, true)) {
        echo "<p>✅ Folder 'uploads' berhasil dibuat</p>";
    } else {
        echo "<p>❌ Gagal membuat folder 'uploads'</p>";
    }
} else {
    echo "<p>✅ Folder 'uploads' sudah ada</p>";
}

// 2. Buat file .htaccess untuk keamanan
$htaccessContent = "# Keamanan folder uploads
<Files *.php>
    Order Allow,Deny
    Deny from all
</Files>

# Hanya izinkan file gambar
<Files ~ \"\\.(jpg|jpeg|png|gif)$\">
    Order Allow,Deny
    Allow from all
</Files>

Options -Indexes";

$htaccessPath = $uploadDir . '/.htaccess';
if (!file_exists($htaccessPath)) {
    if (file_put_contents($htaccessPath, $htaccessContent)) {
        echo "<p>✅ File .htaccess berhasil dibuat</p>";
    }
}

// 3. Buat sample images menggunakan GD (jika tersedia)
if (extension_loaded('gd')) {
    $sampleImages = array(
        'sample-tv.jpg' => array('name' => 'TV', 'color' => array(52, 152, 219)),
        'sample-phone.jpg' => array('name' => 'PHONE', 'color' => array(155, 89, 182)),
        'sample-laptop.jpg' => array('name' => 'LAPTOP', 'color' => array(46, 204, 113))
    );
    
    foreach ($sampleImages as $filename => $data) {
        $filepath = $uploadDir . '/' . $filename;
        
        if (!file_exists($filepath)) {
            // Buat gambar sample 200x200
            $image = imagecreate(200, 200);
            
            // Warna background dan teks
            $backgroundColor = imagecolorallocate($image, 240, 240, 240);
            $textColor = imagecolorallocate($image, $data['color'][0], $data['color'][1], $data['color'][2]);
            $borderColor = imagecolorallocate($image, 200, 200, 200);
            
            // Gambar background dan border
            imagefill($image, 0, 0, $backgroundColor);
            imagerectangle($image, 0, 0, 199, 199, $borderColor);
            
            // Tambahkan teks
            $textX = (200 - strlen($data['name']) * 10) / 2;
            imagestring($image, 3, $textX, 90, $data['name'], $textColor);
            imagestring($image, 2, 60, 110, 'Sample Image', $textColor);
            
            // Simpan sebagai JPEG
            if (imagejpeg($image, $filepath, 80)) {
                echo "<p>✅ Sample image '$filename' berhasil dibuat</p>";
            }
            
            imagedestroy($image);
        } else {
            echo "<p>✅ Sample image '$filename' sudah ada</p>";
        }
    }
} else {
    echo "<p>⚠️ Extension GD tidak tersedia, sample images tidak dapat dibuat</p>";
    echo "<p>💡 Anda dapat mengupload gambar sendiri nanti</p>";
}

// 4. Test write permission
$testFile = $uploadDir . '/test.txt';
if (file_put_contents($testFile, 'test')) {
    unlink($testFile);
    echo "<p>✅ Folder uploads dapat ditulis</p>";
} else {
    echo "<p>❌ Folder uploads tidak dapat ditulis! Periksa permission folder</p>";
}

echo "<hr>";
echo "<h3>🎉 Setup Selesai!</h3>";
echo "<p>📁 Struktur folder yang dibuat:</p>";
echo "<ul>";
echo "<li>📂 uploads/ (folder untuk menyimpan gambar)</li>";
echo "<li>🔒 uploads/.htaccess (file keamanan)</li>";
if (extension_loaded('gd')) {
    echo "<li>🖼️ uploads/sample-tv.jpg</li>";
    echo "<li>🖼️ uploads/sample-phone.jpg</li>";
    echo "<li>🖼️ uploads/sample-laptop.jpg</li>";
}
echo "</ul>";

echo "<p><a href='index.php' style='background: #3498db; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;'>🚀 Mulai Menggunakan Sistem</a></p>";
?>

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup - Toko Elektronik</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background: #f4f4f4;
            line-height: 1.6;
        }
        h2, h3 {
            color: #2c3e50;
        }
        p {
            margin: 10px 0;
        }
        ul {
            margin: 15px 0;
            padding-left: 20px;
        }
        hr {
            margin: 30px 0;
            border: none;
            border-top: 2px solid #3498db;
        }
    </style>
</head>
<body>
    <!-- Content generated by PHP above -->
</body>
</html>